version: '2'
services:
  db:
     image: mysql
     container_name: db
     hostname: mysql
     expose:
      - 3306
     ports:
      - "3306:3306"
     environment:
         MYSQL_USER: root
         MYSQL_ROOT_PASSWORD: csse 
     volumes:
      - ./Database/schema:/docker-entrypoint-initdb.d
      - /var/lib/mysql:/var/lib/mysql
  web:
     build: ./flask_master/
     container_name: app
     ports: 
      - "5000:5000"
     command: python run_server.py
     links:
      - db:mysql
     depends_on:
      - db
     
