version: '2'
services:
  db:
     restart: always
     image: mysql
     hostname: mysql
     container_name: db
     environment:
         MYSQL_ROOT_PASSWORD: root 
     volumes:
      - /Database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /Database/data:/var/lib/mysql
     ports:
      - "3306:3306"
  web:
     build: ./flask_master/
     ports:
      - "5000:5000"
     links:
      - db:mysql
     depends_on:
      - db

