version: '2'
services:
  db:
     image: mysql
     environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: six-dof
     ports:
      - "3306"
  web:
     build: ./flask_master/
     ports:
      - "5000:5000"
     links:
      - db
     depends_on:
      - db
     tty: true
